server:
  port: 5656


spring:
  datasource:
    url: jdbc:h2:file:/D:/DBSpring/dbCMS/testdb
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update

externalDocs: http://api.localhost.com






